-- =============================================================================
-- 002_default_settings.sql — Baseline configuration so a freshly migrated
-- database is immediately usable. Values are editable by an admin at runtime
-- through /api/settings; these are only the starting points.
--
-- Defaults are chosen for the deployment described in the PRD (a single
-- Tanzanian school), but nothing in the code assumes that timezone.
-- =============================================================================

INSERT INTO settings (key, value, description) VALUES
  ('school_name',
   '"Sample Secondary School"'::jsonb,
   'Name shown on the dashboard and on exported reports.'),

  ('timezone',
   '"Africa/Dar_es_Salaam"'::jsonb,
   'IANA timezone. Decides which calendar day a fingerprint punch belongs to.'),

  ('school_start_time',
   '"07:30"'::jsonb,
   'Local time the school day begins. Arrivals at or before this are on time.'),

  ('late_after_time',
   '"07:45"'::jsonb,
   'Local time after which an arrival is recorded as late rather than present.'),

  ('school_end_time',
   '"15:30"'::jsonb,
   'Local time the school day ends; used to interpret check-out punches.'),

  ('attendance_cutoff_time',
   '"23:59"'::jsonb,
   'Local time after which a day is finalised and remaining students marked absent.'),

  ('school_days_of_week',
   '[1,2,3,4,5]'::jsonb,
   'ISO weekdays counted as school days (1 = Monday … 7 = Sunday). Overridden per-date by the school calendar.'),

  ('consecutive_absence_threshold',
   '3'::jsonb,
   'Number of consecutive school-day absences that raises an absentee alert (PRD §7.8).'),

  ('duplicate_punch_window_minutes',
   '2'::jsonb,
   'Punches from the same student within this window are treated as one scan (finger re-tries).'),

  ('minimum_checkout_gap_minutes',
   '60'::jsonb,
   'A later punch is only treated as a check-out once this much time has passed since check-in.'),

  ('auto_finalize_enabled',
   'true'::jsonb,
   'Whether the nightly job automatically marks non-scanning students absent.'),

  ('report_footer_note',
   '"Generated by the Student Fingerprint Attendance System."'::jsonb,
   'Footer line printed on exported PDF reports.')
ON CONFLICT (key) DO NOTHING;
